import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Layout from '../../components/Layout'
import styles from '../../styles/Comments.module.css'
import { ToastContainer, toast } from 'react-toastify';
import { db, storage } from '../../utils/firebase'
import { addDoc, collection, doc, serverTimestamp, updateDoc, query, where, onSnapshot, getDocs, getDoc } from '@firebase/firestore'
import { getDownloadURL, ref, uploadString } from '@firebase/storage'
import 'react-toastify/dist/ReactToastify.css';
import Categories from '../../components/Categories'
import Comments from '../../components/Comments'
import { Store } from '../../utils/Store'
const CommentsPage = ({ comments }) => {
    

    return (
        <>
            <Head>
                <title>HQSocial</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
               
            </Head>
            <Layout>
                <div className={styles.commentsContainer}>
                    <div className={styles.categories}>
                        <Categories />
                    </div>
                    <div className={styles.comments}>
                        {comments ? <Comments comments={comments} /> : null}
                    </div>
                </div>
            </Layout>
        </>
    )
}


export const getServerSideProps = async ({ query: url_query }) => {
    const { id } = url_query
    const postRef = doc(db, "posts", id)
    const postDoc = await getDoc(postRef)
    const comments  = postDoc.data().comments
    

    return {
        props: {
            comments
        }
    }

}

export default CommentsPage