import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from './../components/Layout';
import Categories from './../components/Categories';
import Posts from '../components/Posts';
import { useRouter } from 'next/router';
import { useContext, useEffect } from 'react';
import { Store } from './../utils/Store';
import { db, storage } from '../utils/firebase'
import { addDoc, collection, doc, serverTimestamp, updateDoc, query, where, onSnapshot, getDocs } from '@firebase/firestore'
import { getDownloadURL, uploadString, ref } from 'firebase/storage'

export default function Home({ posts }) {
  const router = useRouter()
  const { state, dispatch } = useContext(Store)
  const { userInfo } = state
  
  useEffect(() => {
    if (!userInfo) router.push('/login')
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>HQSocial</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <div className={styles.homeContainer}>
          <div className={styles.categories}>
            <Categories />
          </div>
          <div className={styles.posts}>
            <Posts posts={posts} />
          </div>
        </div>
      </Layout>
    </div>
  )
}

export const getServerSideProps = async () => {


  const postRef = collection(db, "posts")
  let posts = []
  if (!postRef) return
  const postQuery = query(postRef)
  const querySnapshot = await getDocs(postQuery)
  querySnapshot.docs.forEach(async (snapshot) => {
    const postData = { ...snapshot.data(), postId: snapshot.id }

    posts.push(postData)

  })

  return {
    props: {
      posts: posts
    }
  }
}
